<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUazlr8d\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUazlr8d/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUazlr8d.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUazlr8d\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUazlr8d\appProdProjectContainer([
    'container.build_hash' => 'Uazlr8d',
    'container.build_id' => '0c04715b',
    'container.build_time' => 1622146888,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUazlr8d');
